Add colored scripts output

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -5,6 +5,34 @@ set -e
 BIN_NAME=$(basename "$0")
 COMMAND_NAME=$1
 
+ESC_SEQ="\x1b["
+COL_RESET=$ESC_SEQ"39;49;00m"
+COL_RED=$ESC_SEQ"31;01m"
+COL_GREEN=$ESC_SEQ"32;01m"
+COL_BLUE=$ESC_SEQ"34;01m"
+
+function info () {
+  echo -e "$COL_BLUE""RUNNING: $1$COL_RESET"
+}
+function success () {
+  echo -e "$COL_GREEN""COMPLETED: $1$COL_RESET\n"
+}
+
+function error () {
+  echo -e "$COL_RED""FAILED: $1$COL_RESET\n"
+  exit 1
+}
+
+result () {
+  if [[ "$1" -eq 0 ]]; then
+      success "$2"
+  else
+      error "$2"
+  fi
+
+  return "$1"
+}
+
 help () {
   echo "Usage: $BIN_NAME <command>"
   echo
@@ -17,43 +45,47 @@ help () {
 }
 
 backup () {
-  echo -e "Backing up application preferences"
+  task='Backing up application preferences'
+  info "$task"
   $(which mackup) --force backup
-  echo -e "Backed up application preferences\n"
+  result $? "$task"
 
-  echo -e "Generating Brewfile"
+  task='Generating Brewfile'
+  info "$task"
   $(which brew) bundle --force --file=$DOTFILES/homebrew/Brewfile dump
-  echo -e "Generated Brewfile\n"
+  result $? "$task"
 }
 
 clean () {
-  echo -e "Cleaning up Homebrew packages"
+  task='Cleaning up Homebrew packages'
+  info "$task"
   $(which brew) cleanup
-  echo -e "Cleaned up Homebrew packages"
+  result $? "$task"
 }
 
 macos () {
-  echo -e "Configuring macOS default preferences"
+  task='Configuring macOS default preferences'
+  info "$task"
   $HOME/.dotfiles/macos/defaults.sh
-  echo -e "Configured macOS default preferences\n"
+  result $? "$task"
 }
 
 update () {
-  echo -e "Updating macOS"
+  task='Updating macOS'
   sudo $(which softwareupdate) --install --all
-  echo -e "Updated macOS\n"
+  result $? "$task"
 
-  echo -e "Upgrading Homebrew"
+  task='Upgrading Homebrew'
   $(which brew) update
-  echo -e "Updated Homebrew"
+  result $? "$task"
 
-  echo -e "Updating Homebrew packages"
+  task='Updating Homebrew packages'
   $(which brew) upgrade
-  echo -e "Updated Homebrew packages\n"
+  result $? "$task"
 
-  echo -e "Updating zsh plugins"
+  task='Updating zsh plugins'
   $(which antibody) update
-  echo -e "Updated zsh plugins\n"
+  result $? "$task"
 }
 
 case $COMMAND_NAME in
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-set -e
-
 if [[ ! $(uname) = "Darwin" ]]; then
   error 'unsupported os' # TODO add error message
 fi
@@ -11,6 +9,34 @@ DOTFILES_REPO=https://github.com/aosmialowski/dotfiles.git
 
 sudo -v
 while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2> /dev/null &
+
+ESC_SEQ="\x1b["
+COL_RESET=$ESC_SEQ"39;49;00m"
+COL_RED=$ESC_SEQ"31;01m"
+COL_GREEN=$ESC_SEQ"32;01m"
+COL_BLUE=$ESC_SEQ"34;01m"
+
+function info () {
+  echo -e "$COL_BLUE""RUNNING: $1$COL_RESET"
+}
+function success () {
+  echo -e "$COL_GREEN""COMPLETED: $1$COL_RESET\n"
+}
+
+function error () {
+  echo -e "$COL_RED""FAILED: $1$COL_RESET\n"
+  exit 1
+}
+
+result () {
+  if [[ "$1" -eq 0 ]]; then
+      success "$2"
+  else
+      error "$2"
+  fi
+
+  return "$1"
+}
 
 link () {
   args=("$@")
@@ -42,40 +68,44 @@ link () {
   fi
 }
 
-echo -e "Installing Xcode command line tools"
+task='Installing Xcode command line tools'
+info "$task"
 if [[ ! $(xcode-select --print-path) ]]; then
   xcode-select --install
 
   until [[ $(xcode-select --print-path) ]]; do
-    echo -e "Waiting for Xcode command line tools installation to complete"
     sleep 5
   done
 fi
-echo -e "Installed Xcode command line tools\n"
+result $? "$task"
 
-echo -e "Configuring dotfiles repository"
+task='Configuring dotfiles repository'
+info "$task"
 if [[ ! -d $DOTFILES_DIR ]]; then
   $(which git) clone $DOTFILES_REPO $DOTFILES_DIR
 else
   cd $DOTFILES_DIR && $(which git) pull
 fi
-echo -e "Configured dotfiles repository\n"
+result $? "$task"
 
 cd $DOTFILES_DIR
 
-echo -e "Creating required directories"
+task='Creating required directories'
+info "$task"
 [ -d $HOME/bin ] || mkdir $HOME/bin
 [ -d $HOME/.mackup ] || mkdir $HOME/.mackup
 [ -d $HOME/.zsh ] || mkdir $HOME/.zsh
 [ -d $HOME/Workspace ] || mkdir $HOME/Workspace
-echo -e "Created required directories"
+result $? "$task"
 
-echo -e "Applying required files permission"
+task="Applying required files permission"
+info "$task"
 chmod +x $DOTFILES_DIR/bin/dotfiles
 chmod +x $DOTFILES_DIR/macos/*.sh
-echo -e "Applied required files permission\n"
+result $? "$task"
 
-echo -e "Installing dotfiles"
+task='Installing dotfiles'
+info "$task"
 link '~/.curlrc' 'curl/curlrc' true
 link '~/.editorconfig' 'editorconfig/editorconfig' true
 link '~/.gitattributes' 'git/gitattributes' true
@@ -89,42 +119,51 @@ link '~/.zsh/options.zsh' 'zsh/options.zsh' true
 link '~/.zsh/plugins.txt' 'zsh/plugins.txt' true
 link '~/.zshrc' 'zsh/zshrc' true
 link '~/bin/dotfiles' 'bin/dotfiles' true
-echo -e "Installed dotfiles\n"
+result $? "$task"
 
 if [[ ! $(which brew) ]]; then
-  echo -e "Installing Homebrew"
+  task='Installing Homebrew'
+  info "$task"
   yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-  echo -e "Installed Homebrew\n"
+  result $? "$task"
 else
-  echo -e "Updating Homebrew"
+  task='Updating Homebrew'
+  info "$task"
   $(which brew) update
-  echo -e "Updated Homebrew\n"
+  result $? "$task"
 
-  echo -e "Upgrading Homebrew"
+  task='Upgrading Homebrew'
+  info "$task"
   $(which brew) upgrade
-  echo -e "Upgraded Homebrew\n"
+  result $? "$task"
 fi
 
-echo -e "Installing Homebrew packages"
+task='Installing Homebrew packages'
+info "$task"
 $(which brew) bundle --file=$DOTFILES_DIR/homebrew/Brewfile --no-lock install
-echo -e "Installed Homebrew packages\n"
+result $? "$task"
 
-echo -e "Cleaning up Homebrew packages"
+task='Cleaning up Homebrew packages'
+info "$task"
 $(which brew) cleanup
-echo -e "Cleaned up Homebrew packages\n"
+result $? "$task"
 
-echo -e "Installing zsh plugins"
+task='Installing zsh plugins'
+info "$task"
 $(which antibody) bundle < $HOME/.zsh/plugins.txt > $HOME/.zsh/plugins.zsh
-echo -e "Installed zsh plugins\n"
+result $? "$task"
 
-echo -e "Updating zsh plugins"
+task='Updating zsh plugins'
+info "$task"
 $(which antibody) update
-echo -e "Updated zsh plugins\n"
+result $? "$task"
 
-echo -e "Restoring application preferences"
+task='Restoring application preferences'
+info "$task"
 $(which mackup) --force restore
-echo -e "Restored application preferences\n"
+result $? "$task"
 
-echo -e "Configuring macos default settings"
+task='Configuring macos default settings'
+info "$task"
 $HOME/.dotfiles/macos/defaults.sh
-echo -e "Configured macos default settings\n"
+result $? "$task"
